services:
  - type: web
    name: promptwise-backend
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
